### ISSUE TITLE
Are there example apps with SQL storage?

### ISSUE THREAD

**Issue by DavidBruant** [dckc/awesome-ocap#49]
Hi, 

First off, thank you very much for this repo and all the references, it's amazing :star_struck: 

And also, because constraints, i need to implement a web application with an ocaps authorization model and store things in SQL. Are there existing open source sample applications to find inspiration for the database table design? Or articles?

Thanks!

**Comment by dckc** [comment]
You're welcome!

In the [Agoric SDK](https://github.com/Agoric/agoric-sdk), sqlite is used for durable storage of both

 - [kernel state](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/docs/state.md)
 - [Vat Secondary Storage](https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/docs/virtual-objects.md)

Both use [swingstore](https://github.com/Agoric/agoric-sdk/tree/master/packages/swing-store), which is a key-value store implemented in sqlite tables.

That's the only example that comes to mind just now.

**Comment by DavidBruant** [comment]
Thank you for your answers :pray:

**Comment by dckc** [comment]
Oh... Maybe Belay too?

 - 2012-03: [Belay Demo](https://www.youtube.com/watch?v=2_5p6S2eW8s&t=1s) 5min. Mark Lentczner, Security Team, Google

I don't have the source handy, but it shouldn't be too hard to find.
